name: Project Info

on:
  workflow_dispatch:
    inputs:
      project_number:
        type: number
        required: true

  workflow_call:
    inputs:
      project_number:
        required: true
        type: string
    secrets:
       APP_ID:
         required: false
       CLIENT_PEM:
         required: false
    outputs:
      project_id:
        description: "Project node_id"
        value: ${{ jobs.project-info.outputs.node_id }}
jobs:
  project-info:
    runs-on: ubuntu-latest
    outputs:
      node_id: ${{ steps.project-info.outputs.node_id }}
    steps:
      - name: Get Project Info
        id: project-info
        uses: ./.github/actions/project-info
        with:
          APP_ID: ${{ secrets.APP_ID }}
          CLIENT_PEM: ${{ secrets.CLIENT_PEM }}
          project_number: ${{ github.event.inputs.project_number }}
